sudo: required
language: minimal
services:
- docker
script:
- scripts/build.sh ${TRAVIS_BRANCH} linux
- scripts/build.sh ${TRAVIS_BRANCH} darwin
- scripts/update_installer.sh ${TRAVIS_BRANCH}
deploy:
- provider: releases
  api_key:
    secure: aW4qydYdCKRGIxfnTovRXsK8GJr2hN23g1iZEGKR0+/iAQbhdrat5r1IDor3mY0fu0+94aEg/KUpB567QKkVR1pZNDs9UqjGLFOTXyJqzP9G8HKvh7LBLckXsenRJszTef3/lblt0c26CpXH0jg1Anpf2N1MlgE0cL9GSg6E7lXJXL7MJahBAzi1GN1Wd4vvjfeavp04G3BUG8/HgcaDFnhZu/0fYesU8r6nBjKBerg66bDJjLNXwqETCJFdp3A4vgLQypCHKl3tqNy44KF5IngT5t5wNMPHsvBPXBZZsr/8NPn9qq5pcZXqKS3YAZM2rzaJ5imw9ayd/j+tl8iKq+ULbeWV+FD3PkPwphRzUyb7Slrmppg0E82TZvqRP/B98HGgVID9vtkH6CI3HotYhtZz78Hf+NLvwzPkUwA/cxHiQQmjfx7+k9J/Sc9Kn98xQiGU+ZBg8kem46jMBGNlYJQ4wmBaS4hr3envz1ym85uwRwAIlFAXne3MwelLgt+BLEc3urzZhihWl54inw7HGYmA3rzHNK3KOTB3jO1GBDLn4O2wMLS5L+n5lErtxT+RTRxicvThevYRNAF7im3Mt56ijb6w1otZdOSti2F3fvoBQqJv3WZQL/sxbFixtj5PCyCiF4I8b2TuWf4TMN94vrrXnSKjQwvamZMQ+n94WfE=
  file_glob: true
  file:
  - bin/*.tar.gz
  - bin/install.sh
  skip_cleanup: true
  on:
    tags: true
- provider: script
  script: bash scripts/publish_docker.sh ${TRAVIS_BRANCH}
  on:
    tags: true
- provider: script
  script: bash scripts/publish_docker.sh ${TRAVIS_BRANCH} latest
  on:
    branch: master
env:
  global:
  - secure: UT7gCNH6KnKPPdWJyE3TlRdgcGvpdrw2ERXVVQImXAbSuTpbiJ+6EuY3ZTUFQtD1zw9w44cnLCISm/AxhFg5jl0v/YeUFNAUa8NJCVPZq41YPEx76ucxD5IOPzhFqH1oT7Fk40ycKI8i4+E2jt71frdBs0sOkvpJN2Av1BV2tvZoXzUHThd5w3U6sZue6Ra7H19nfX67PHLBBj5Li+XyDsMLBkORBEkcZpDBDjI7akNijcoQRH0xpKOyWxsFAhGh7uyWd23uq/hmhZK/+dVAyIsSydL1i39AlCzfTLRrPNAw3FVKxNvS7jk0PujMMDC2qzdEkclB29Z+Ht1c8ykcDT/tFhhf0hQPOvAhuRVsyrbXRvj3bNz1Ba1peCpdgzOYiGLXX7it+ANFEF+tYjoScdg8Pah/rVEF+AUrDxSQFUnQDcLl3Jnf48nHxCp8V3Tz7eweJJc+J365pG0dPed8Z7SlnlHdQ7pT86oV6lYTgNTmQImdsbgxx/BjW1zYlDHj5qxL/mjPOSTNaulTp/WXt/DfcxOMv459U6obqUvhl5loJFW/3UQf68QFbfoFGfxotEzheaHQEyw/hJ4aDerAeE4ZsDFVOQP5WVQNFtd9eQr8ZUh+wYWWH8VbJ3T0Z9HaVQPLbH6KZJ/hIvb3WqA9YIUWUsWzCn70wuVeDAdNFeM=
  - secure: Bp625TFe0xKPrl8+hPFd0CumQr9XFkuwN6iUHjYXVd8uJS0EbJKXQQSLQAHL+9kNi8q8xU/ZaYjaL6374hLd2lnDhqi8uTGXDaWiFe3iWwhfxM7NMfob4siOXBT14b1ddEMhR1trrJL0A/xMCP5f2xeDhya8VZPhOQEtBZjH4be1Y3DkmjzV8gTJ1o9IyuhPf/O861TXu2lS8tkRSjn4lnbGu8dALt7Q+/DbrmnQiVVSvJ0ximYZ9kuUt6SvROwwrmx430hVZ+sa6be8S0A83mAuiDxLviezOWmjzWOwKKF9hQfdfukgVfoxyIxbD/alJvrmeby5ggPNWV0LHr9QDiruTw7z0rveVI0HnqY7QVDO9Hf9L6oaefRT0b5vigbJRM3xdHdYfzDtn36SZ0ESy6Filh9Q2fBVnZ0bpEk6JEK+5Dsl0ozLqIYhdDiG+BIIGEBvwKYkcf2zJJH/vbSVkTayeA4bFjHpDCzZ22AN40xmL371uErQVU+SzEas3k6rNB6RP0O+cfbE/nFeg57PDsYITry+q3KfjTDVyHXxSxu5rah/yjxm0qVkXg0pStlUzj8z5Q+4u2/iUHolH/fiXgSq/NbdFvkHDyFL3RIsqUyDFzhs1vP+AOFM6vReTDtRLJS7hTL/zGNiNkSzN5aSHRoHxt1Afld+EzIuJijmFDw=
